version: '3.8'

services:
  frontend:
    build:
      context: ./templates/frontend  
      dockerfile: Dockerfile
    image: subhra1608/mlops_23:frontend-latest # Update image name with repository name and tag
    ports:
      - "3000:3000"
    depends_on:
      - backend
   

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: subhra1608/mlops_23:backend-latest # Update image name with repository name and tag
    ports:
      - "2060:2060"
    volumes:
      - ./elasticSearch_log.py:/app/elasticSearch_log.py  # Mount the Elasticsearch log file
    environment:
      - PYTHONPATH=/app  # Set the Python path to include the app directory
