---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Docker Compose
      command: /usr/local/bin/docker-compose up -d

      args:
        chdir: /home/subhrajyotisingh/Desktop/working
      become: true